#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Common
{
    
    #line 2 "..\..\Razor\Common\Copyright.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Copyright : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("/**\r\n * Copyright (C) ");


            
            #line 4 "..\..\Razor\Common\Copyright.cshtml"
            Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" YOUR_COMPANY_HERE, Inc. All Rights Reserved.\r\n */ ");


        }
    }
}
#pragma warning restore 1591
