#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Common
{
    
    #line 2 "..\..\Razor\Common\RegionBeg.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Razor\Common\RegionBeg.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class RegionBeg : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Razor\Common\RegionBeg.cshtml"

    public String RegionLabel { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n");


            
            #line 7 "..\..\Razor\Common\RegionBeg.cshtml"
Write((new Region { Tag = "BEG", RegionLabel = RegionLabel }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
