#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Service
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Razor\Service\ServiceRazor.cshtml"
    using Parse;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Razor\Service\ServiceRazor.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Razor\Service\ServiceRazor.cshtml"
    using Razor.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ServiceRazor : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 7 "..\..\Razor\Service\ServiceRazor.cshtml"

    public ServiceParser TheService { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


            
            #line 10 "..\..\Razor\Service\ServiceRazor.cshtml"
  
    //const strin wontCompile;
    const string overrideMethodsRegion = "Override Methods";
    const string actionMethodsRegion = "Action Methods";
    const string staticInitRegion = "Static Initialization";
    const string ctorRegion = "ctor";


            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("\r\n");


            
            #line 19 "..\..\Razor\Service\ServiceRazor.cshtml"
  
    var copyright = new Copyright();
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Razor\Service\ServiceRazor.cshtml"
Write(copyright.TransformText());

            
            #line default
            #line hidden
            
            #line 21 "..\..\Razor\Service\ServiceRazor.cshtml"
                              ;


            
            #line default
            #line hidden


WriteLiteral("\r\npackage ");


            
            #line 24 "..\..\Razor\Service\ServiceRazor.cshtml"
   Write(TheService.Package);

            
            #line default
            #line hidden
WriteLiteral(";\r\n");




            
            #line 25 "..\..\Razor\Service\ServiceRazor.cshtml"
             WriteLiteral("\r\nimport android.content.Intent;\r\nimport com.wildtangent.common.log.WrappingLog;\r" +
"\nimport ");

            
            #line default
            #line hidden
            
            #line 28 "..\..\Razor\Service\ServiceRazor.cshtml"
         
            
            #line default
            #line hidden
            
            #line 28 "..\..\Razor\Service\ServiceRazor.cshtml"
    Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 28 "..\..\Razor\Service\ServiceRazor.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral(".broadcast.*;\r\nimport com.laskcon.android.");


            
            #line 29 "..\..\Razor\Service\ServiceRazor.cshtml"
                      Write(TheService.Type.ToString());

            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 30 "..\..\Razor\Service\ServiceRazor.cshtml"
 if (TheService.LocalRedirector)
{

            
            #line default
            #line hidden
WriteLiteral("import android.content.IntentFilter;\r\n");


            
            #line 33 "..\..\Razor\Service\ServiceRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 34 "..\..\Razor\Service\ServiceRazor.cshtml"
 if(TheService.Actions.OutgoingActions.Count > 0)
{ 

            
            #line default
            #line hidden
WriteLiteral("import ");


            
            #line 36 "..\..\Razor\Service\ServiceRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 36 "..\..\Razor\Service\ServiceRazor.cshtml"
      Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 36 "..\..\Razor\Service\ServiceRazor.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral(".broadcast.");


            
            #line 36 "..\..\Razor\Service\ServiceRazor.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Razor\Service\ServiceRazor.cshtml"
                                       Write(ClassNames.Broadcaster(TheService));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                               
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 37 "..\..\Razor\Service\ServiceRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 38 "..\..\Razor\Service\ServiceRazor.cshtml"
 foreach (var action in TheService.Actions.IncomingActions)
{

            
            #line default
            #line hidden
WriteLiteral("import ");


            
            #line 40 "..\..\Razor\Service\ServiceRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 40 "..\..\Razor\Service\ServiceRazor.cshtml"
      Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 40 "..\..\Razor\Service\ServiceRazor.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral(".broadcast.incoming.");


            
            #line 40 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                     
            
            #line default
            #line hidden
            
            #line 40 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                Write(action.IntentClassName(TheService));

            
            #line default
            #line hidden
            
            #line 40 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                                        
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 41 "..\..\Razor\Service\ServiceRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 42 "..\..\Razor\Service\ServiceRazor.cshtml"
 foreach (var action in TheService.Actions.ExternalActions)
{

            
            #line default
            #line hidden
WriteLiteral("import ");


            
            #line 44 "..\..\Razor\Service\ServiceRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 44 "..\..\Razor\Service\ServiceRazor.cshtml"
      Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 44 "..\..\Razor\Service\ServiceRazor.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral(".broadcast.external.");


            
            #line 44 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                     
            
            #line default
            #line hidden
            
            #line 44 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                Write(action.IntentClassName(TheService));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                                        
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 45 "..\..\Razor\Service\ServiceRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 46 "..\..\Razor\Service\ServiceRazor.cshtml"
 foreach(var imp in TheService.Imports)
{

            
            #line default
            #line hidden
WriteLiteral("import ");


            
            #line 48 "..\..\Razor\Service\ServiceRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 48 "..\..\Razor\Service\ServiceRazor.cshtml"
      Write(imp);

            
            #line default
            #line hidden
            
            #line 48 "..\..\Razor\Service\ServiceRazor.cshtml"
               
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 49 "..\..\Razor\Service\ServiceRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("/*\r\n");


            
            #line 51 "..\..\Razor\Service\ServiceRazor.cshtml"
 if(string.IsNullOrWhiteSpace(TheService.ClassOverview)){

            
            #line default
            #line hidden
WriteLiteral(" * TODO: Give an overview of what this public class does and how other components" +
" utilize it      \r\n");


            
            #line 53 "..\..\Razor\Service\ServiceRazor.cshtml"
}else
{
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Razor\Service\ServiceRazor.cshtml"
Write(TheService.ClassOverview);

            
            #line default
            #line hidden
            
            #line 55 "..\..\Razor\Service\ServiceRazor.cshtml"
                             
}

            
            #line default
            #line hidden

            
            #line 57 "..\..\Razor\Service\ServiceRazor.cshtml"
WriteLiteral(" *\r\n * This class requires an entry in the manifest to register this service. \r\n " +
"* Example entry: <service android:name=\"");

            
            #line default
            #line hidden
            
            #line 59 "..\..\Razor\Service\ServiceRazor.cshtml"
                                           
            
            #line default
            #line hidden
            
            #line 59 "..\..\Razor\Service\ServiceRazor.cshtml"
                                      Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 59 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                              
            
            #line default
            #line hidden

            
            #line 59 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                               WriteLiteral(".");

            
            #line default
            #line hidden
            
            #line 59 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                  
            
            #line default
            #line hidden
            
            #line 59 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                             Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 59 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                                  
            
            #line default
            #line hidden
WriteLiteral("\" android:exported=\"false\" />\r\n */\r\npublic final class ");


            
            #line 61 "..\..\Razor\Service\ServiceRazor.cshtml"
              Write(TheService.Name);

            
            #line default
            #line hidden
WriteLiteral(" extends ");


            
            #line 61 "..\..\Razor\Service\ServiceRazor.cshtml"
                                       Write(TheService.Type.ToString());

            
            #line default
            #line hidden
WriteLiteral(" {\r\n\r\n    ");


            
            #line 63 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionBeg { RegionLabel = staticInitRegion }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");



WriteLiteral("\r\n    /**\r\n     *  Initialization of the static components of the class\r\n     */\r" +
"\n    public static void initialize(){\r\n");


            
            #line 69 "..\..\Razor\Service\ServiceRazor.cshtml"
         if (TheService.LocalRedirector) { 

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("registerRedirectorFilter(); \r\n");


            
            #line 71 "..\..\Razor\Service\ServiceRazor.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    }\r\n\r\n    ");


            
            #line 74 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionEnd { RegionLabel = staticInitRegion }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 76 "..\..\Razor\Service\ServiceRazor.cshtml"
 if (TheService.Type.ToString().Contains("IntentService"))
{
    
            
            #line default
            #line hidden
            
            #line 78 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionBeg { RegionLabel = ctorRegion }).TransformText().Trim());

            
            #line default
            #line hidden
            
            #line 78 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                          

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("    public ");


            
            #line 80 "..\..\Razor\Service\ServiceRazor.cshtml"
               
            
            #line default
            #line hidden
            
            #line 80 "..\..\Razor\Service\ServiceRazor.cshtml"
          Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 80 "..\..\Razor\Service\ServiceRazor.cshtml"
                               
            
            #line default
            #line hidden
WriteLiteral("(){\r\n");



WriteLiteral("        super(");


            
            #line 81 "..\..\Razor\Service\ServiceRazor.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 81 "..\..\Razor\Service\ServiceRazor.cshtml"
             Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 81 "..\..\Razor\Service\ServiceRazor.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral(".class.getSimpleName());\r\n");



WriteLiteral("    }\r\n");



WriteLiteral("    \r\n");


            
            #line 84 "..\..\Razor\Service\ServiceRazor.cshtml"
    
            
            #line default
            #line hidden
            
            #line 84 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionEnd { RegionLabel = ctorRegion }).TransformText().Trim());

            
            #line default
            #line hidden
            
            #line 84 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                          
}

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 87 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new ServiceLocalRedirector { TheService = TheService }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");


            
            #line 89 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionBeg { RegionLabel = overrideMethodsRegion }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");


WriteLiteral("@Override\r\n    protected void initActionMethods() {\r\n     \r\n        try {\r\n");


            
            #line 95 "..\..\Razor\Service\ServiceRazor.cshtml"
  
    var registerMethod = TheService.Type.ToString().Contains("IntentService") ? "registerAction" : "registerActionCallable";


            
            #line default
            #line hidden

            
            #line 98 "..\..\Razor\Service\ServiceRazor.cshtml"
         foreach (var action in TheService.Actions.IncomingAndExternalActions)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");


            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                
            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
           Write(registerMethod);

            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                               
            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                   
            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                              Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                     
            
            #line default
            #line hidden
WriteLiteral(".");


            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                         
            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                    Write(action.FieldName(TheService));

            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                                                      
            
            #line default
            #line hidden
WriteLiteral(", \"on");


            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                                                              
            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                                                         Write(action.MixedCaseName);

            
            #line default
            #line hidden
            
            #line 100 "..\..\Razor\Service\ServiceRazor.cshtml"
                                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral("\");\r\n");


            
            #line 101 "..\..\Razor\Service\ServiceRazor.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        } catch (NoSuchMethodException e) {\r\n           WrappingLog.e(e.getLocali" +
"zedMessage());\r\n        }\r\n    }\r\n            \r\n\r\n    ");


            
            #line 108 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionEnd { RegionLabel = overrideMethodsRegion }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");


            
            #line 110 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionBeg { RegionLabel = actionMethodsRegion }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n    //\r\n    // Service Defined Intents\r\n    //\r\n");


            
            #line 114 "..\..\Razor\Service\ServiceRazor.cshtml"
 foreach (var action in TheService.Actions.IncomingActions)
{

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 116 "..\..\Razor\Service\ServiceRazor.cshtml"
  Write((new ServiceOnActionMethod { TheAction = action, TheService = TheService }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("    ");

WriteLiteral("\r\n");


            
            #line 118 "..\..\Razor\Service\ServiceRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    //\r\n    // Externally Defined Intents\r\n    //\r\n");


            
            #line 122 "..\..\Razor\Service\ServiceRazor.cshtml"
 foreach (var action in TheService.Actions.ExternalActions)
{

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 124 "..\..\Razor\Service\ServiceRazor.cshtml"
  Write((new ServiceOnActionMethod { TheAction = action, TheService = TheService }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("    ");

WriteLiteral("\r\n");


            
            #line 126 "..\..\Razor\Service\ServiceRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 127 "..\..\Razor\Service\ServiceRazor.cshtml"
Write((new RegionEnd { RegionLabel = actionMethodsRegion }).TransformText().Trim());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n}");




        }
    }
}
#pragma warning restore 1591
