#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Service
{
    
    #line 2 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 3 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
    using Parse;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ServiceOnActionMethod : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 8 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"

    public ActionBase TheAction { get; set; }
    public ServiceParser TheService { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 12 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
  
    var methodName = "on" + TheAction.MixedCaseName;


            
            #line default
            #line hidden
WriteLiteral("    ");



            
            #line 15 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
     WriteLiteral("@SuppressWarnings(\"unused\")//This method is invoked using reflection\r\n    private" +
" void ");

            
            #line default
            #line hidden
            
            #line 16 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 16 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
              Write(methodName);

            
            #line default
            #line hidden
            
            #line 16 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                              
            
            #line default
            #line hidden

            
            #line 16 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                               WriteLiteral("(final Intent intent){\r\n\r\n        if(!");

            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
              
            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
         Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                
            
            #line default
            #line hidden

            
            #line 18 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                 WriteLiteral(".");

            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                               Write(TheAction.ValidationMethodName);

            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                                                   
            
            #line default
            #line hidden
WriteLiteral("(intent)) return;\r\n");



WriteLiteral("        ");


            
            #line 19 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                       
            
            #line default
            #line hidden
            
            #line 19 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                  Write(TheAction.IntentClassName(TheService));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                             
            
            #line default
            #line hidden

            
            #line 19 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                              WriteLiteral(" castIntent = new ");

            
            #line default
            #line hidden
            
            #line 19 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                                                  
            
            #line default
            #line hidden
            
            #line 19 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                                             Write(TheAction.IntentClassName(TheService));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("(intent);\r\n\r\n");


            
            #line 21 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
         foreach (var key in TheAction.ParamExtraKeys)
        {
            foreach (var ex in TheService.Extras.DistinctExtras)
            {
                if (ex.Name != key)
                {
                    continue;
                }

            
            #line default
            #line hidden
WriteLiteral("        final ");


            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
             Write(ex.Type);

            
            #line default
            #line hidden
            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                         Write(ex.ParamName());

            
            #line default
            #line hidden
            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                             
            
            #line default
            #line hidden
WriteLiteral(" = castIntent.");


            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                              
            
            #line default
            #line hidden
            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                         Write(ex.GetMethodName());

            
            #line default
            #line hidden
            
            #line 29 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
                                                                                 
            
            #line default
            #line hidden
WriteLiteral("();\r\n");


            
            #line 30 "..\..\Razor\Service\ServiceOnActionMethod.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        /*\r\n         *  TODO: Implement functionality\r\n         */\r\n    }");


        }
    }
}
#pragma warning restore 1591
