#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Service
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
    using Parse;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ServiceLocalRedirector : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"

    private const string regionLabel = "Local Broadcast Receiver";
    public ServiceParser TheService { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
Write((new RegionBeg { RegionLabel = regionLabel }).TransformText().Trim());

            
            #line default
            #line hidden

            
            #line 8 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                                           WriteLiteral("\r\n    private static final LocalBroadcastRedirector _redirector = new LocalBroadc" +
"astRedirector(");

            
            #line default
            #line hidden
            
            #line 9 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                                                               
            
            #line default
            #line hidden
            
            #line 9 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                                                          Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 9 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                                                                               
            
            #line default
            #line hidden
WriteLiteral(".class);\r\n\r\n    /**\r\n     * Register redirector filters\r\n     */\r\n    private sta" +
"tic void registerRedirectorFilter() {\r\n\r\n        IntentFilter filter = new Inten" +
"tFilter();\r\n\r\n");


            
            #line 18 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
 foreach (var action in TheService.Actions.IncomingAndExternalActions)
{

            
            #line default
            #line hidden
WriteLiteral("        filter.addAction(");


            
            #line 20 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                             
            
            #line default
            #line hidden
            
            #line 20 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                        Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                               
            
            #line default
            #line hidden
WriteLiteral(".");


            
            #line 20 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                                   
            
            #line default
            #line hidden
            
            #line 20 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                              Write(action.FieldName(TheService));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
                                                                                                
            
            #line default
            #line hidden
WriteLiteral(");\r\n");


            
            #line 21 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
}

            
            #line default
            #line hidden


WriteLiteral("\r\n        _redirector.registerLocalBroadcastReceiver(filter);\r\n    }\r\n\r\n    ");


            
            #line 31 "..\..\Razor\Service\ServiceLocalRedirector.cshtml"
Write((new RegionEnd { RegionLabel = regionLabel }).TransformText().Trim());

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
