#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Service.Receiver
{
    
    #line 2 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    using Parse;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    using Razor.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ReceiverRazor : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 9 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"

    public ServiceParser TheService { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 12 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
  
    //const strin wontCompile;
    var list = string.Join(".equals(action) || \r\n                    ", TheService.Actions.ExternalActions.Where(item => item.Source == ExternalAction.BroadcastSource.Android).Select(item => (ClassNames.IntentBase(TheService) + "." + item.FieldName(TheService))));


            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("\r\n");


            
            #line 18 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
  
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
Write(new Copyright().TransformText());

            
            #line default
            #line hidden
            
            #line 19 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                      ;


            
            #line default
            #line hidden
WriteLiteral("\r\n");




            
            #line 22 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
             WriteLiteral("\r\npackage ");

            
            #line default
            #line hidden
            
            #line 23 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
          
            
            #line default
            #line hidden
            
            #line 23 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
     Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 23 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                             
            
            #line default
            #line hidden
WriteLiteral(".receiver;\r\n\r\n");




            
            #line 25 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
             WriteLiteral("\r\nimport android.content.BroadcastReceiver;\r\nimport android.content.ComponentName" +
";\r\nimport android.content.Context;\r\nimport android.content.Intent;\r\n\r\nimport com" +
".laskon.stubs.StringUtils;\r\nimport ");

            
            #line default
            #line hidden
            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
         
            
            #line default
            #line hidden
            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                            
            
            #line default
            #line hidden

            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                             WriteLiteral(".");

            
            #line default
            #line hidden
            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                           Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                
            
            #line default
            #line hidden

            
            #line 32 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                 WriteLiteral(";\r\nimport ");

            
            #line default
            #line hidden
            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
         
            
            #line default
            #line hidden
            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
    Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                            
            
            #line default
            #line hidden

            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                             WriteLiteral(".broadcast.");

            
            #line default
            #line hidden
            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                          
            
            #line default
            #line hidden
            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                     Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                                            
            
            #line default
            #line hidden

            
            #line 33 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                                             WriteLiteral(";\r\n\r\n/**\r\n * Listens for Android broadcasts (as opposed to local broadcasts) and " +
"redirects desired intents\r\n * to the ");

            
            #line default
            #line hidden
            
            #line 37 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
       Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 37 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                            
            
            #line default
            #line hidden

            
            #line 37 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                             WriteLiteral(".\r\n * The manifest will need an entry like\r\n * <receiver android:name=\"");

            
            #line default
            #line hidden
            
            #line 39 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                             
            
            #line default
            #line hidden
            
            #line 39 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                        Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 39 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                
            
            #line default
            #line hidden

            
            #line 39 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                 WriteLiteral(".receiver.");

            
            #line default
            #line hidden
            
            #line 39 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                             
            
            #line default
            #line hidden
            
            #line 39 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                        Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 39 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                                             
            
            #line default
            #line hidden
WriteLiteral("Receiver\">\r\n * <intent-filter>\r\n");


            
            #line 41 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
 foreach(string actionValue in TheService.Actions.ExternalActions.Where(item => item.Source == ExternalAction.BroadcastSource.Android).Select(item => item.Value))
    {

            
            #line default
            #line hidden
WriteLiteral(" * <action android:name=\"");


            
            #line 43 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                             
            
            #line default
            #line hidden
            
            #line 43 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                        Write(actionValue);

            
            #line default
            #line hidden
            
            #line 43 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                         
            
            #line default
            #line hidden
WriteLiteral("\" />  \r\n");


            
            #line 44 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 45 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
WriteLiteral(" * </intent-filter>\r\n * </receiver>\r\n *\r\n */\r\npublic final class ");

            
            #line default
            #line hidden
            
            #line 49 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                     
            
            #line default
            #line hidden
            
            #line 49 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 49 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                     
            
            #line default
            #line hidden
WriteLiteral("Receiver extends BroadcastReceiver {\r\n    ");



            
            #line 50 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
     WriteLiteral("@Override\r\n    public void onReceive(final Context context, final Intent intent) " +
"{\r\n        if (null != intent) {\r\n            final String action = intent.getAc" +
"tion();\r\n            if (!StringUtils.isNullOrWhiteSpace(action) && (");

            
            #line default
            #line hidden
            
            #line 54 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                              
            
            #line default
            #line hidden
            
            #line 54 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                         Write(list);

            
            #line default
            #line hidden
            
            #line 54 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                                   
            
            #line default
            #line hidden

            
            #line 54 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                                    WriteLiteral(".equals(action))) {\r\n                final Intent i = new Intent(intent);\r\n      " +
"          i.setComponent(new ComponentName(context, ");

            
            #line default
            #line hidden
            
            #line 56 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                       Write(TheService.Name);

            
            #line default
            #line hidden
            
            #line 56 "..\..\Razor\Service\Receiver\ReceiverRazor.cshtml"
                                                                            
            
            #line default
            #line hidden
WriteLiteral(".class));\r\n                context.startService(i);\r\n            }\r\n        }\r\n  " +
"  }\r\n}");


        }
    }
}
#pragma warning restore 1591
