#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Service.Broadcast
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
    using Parse;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
    using Razor.Service;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
    using Razor.Service.Broadcast;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class IntentFactoryRazor : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 6 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"

    public ServiceParser TheService { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\r\n");



WriteLiteral("\r\n");


            
            #line 10 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
  
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
Write(new Copyright().TransformText());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                      ;


            
            #line default
            #line hidden



            
            #line 13 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
             WriteLiteral("\r\npackage ");

            
            #line default
            #line hidden
            
            #line 14 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
          
            
            #line default
            #line hidden
            
            #line 14 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
     Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 14 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                             
            
            #line default
            #line hidden
WriteLiteral(".broadcast;\r\n");



WriteLiteral("\r\n");


            
            #line 16 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
 foreach (var action in TheService.Actions.IncomingActions)
{

            
            #line default
            #line hidden
WriteLiteral("import ");


            
            #line 18 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
      Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral(".broadcast.incoming.");


            
            #line 18 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                     
            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                Write(action.IntentClassName(TheService));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                                                        
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 19 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 20 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
 foreach(var imp in TheService.Imports)
{

            
            #line default
            #line hidden
WriteLiteral("import ");


            
            #line 22 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 22 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
      Write(imp);

            
            #line default
            #line hidden
            
            #line 22 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
               
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 23 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n/**\r\n * The factory create functions build intents to be sent to ");


            
            #line 26 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                       Write(TheService.Name);

            
            #line default
            #line hidden
WriteLiteral(".\r\n *\r\n * Intents this service broadcasts are not created here.\r\n * External even" +
"ts this service listens are not created here.\r\n*/\r\npublic final class ");


            
            #line 31 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
              Write(ClassNames.IntentFactory(TheService));

            
            #line default
            #line hidden
WriteLiteral("{\r\n");


            
            #line 32 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
 foreach (var action in TheService.Actions.IncomingActions)
{

            
            #line default
            #line hidden
WriteLiteral("    /**\r\n");


            
            #line 35 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
    if (!string.IsNullOrWhiteSpace(action.ClassCommentReason))
    {

            
            #line default
            #line hidden
WriteLiteral("     * ");


            
            #line 37 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 37 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
      Write(action.ClassCommentReason);

            
            #line default
            #line hidden
            
            #line 37 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                     
            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 38 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("     * TODO: Add useful comment about what this intent will do\r\n");


            
            #line 42 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("     *\r\n");


            
            #line 44 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
      foreach (var key in action.ParamExtraKeys)
      {
        foreach (var ex in TheService.Extras.InternalAndPublicExtras)
        {
if (ex.Name != key) {continue;}

            
            #line default
            #line hidden
WriteLiteral("     * ");


WriteLiteral("@param ");


            
            #line 49 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
            Write(ex.ParamName());

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 50 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
        }
      }

            
            #line default
            #line hidden
WriteLiteral("     *\r\n");



WriteLiteral("     * ");


WriteLiteral("@return instance of ");


            
            #line 53 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                         Write(action.IntentClassName(TheService));

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("     */\r\n");


            
            #line 55 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    public static ");


            
            #line 56 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
               Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
WriteLiteral(" create");


            
            #line 56 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                               
            
            #line default
            #line hidden
            
            #line 56 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                          Write(action.MixedCaseName);

            
            #line default
            #line hidden
            
            #line 56 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                                                    
            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 56 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                                                        
            
            #line default
            #line hidden
            
            #line 56 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                                                   Write(action.ParamsDeclarations(TheService));

            
            #line default
            #line hidden
            
            #line 56 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                                                                                              
            
            #line default
            #line hidden
WriteLiteral(") {\r\n");



WriteLiteral("        return new ");


            
            #line 57 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                       
            
            #line default
            #line hidden
            
            #line 57 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                  Write(action.IntentClassName(TheService));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                          
            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 57 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                              
            
            #line default
            #line hidden
            
            #line 57 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                         Write(action.ParamsNames((TheService)));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
                                                                                               
            
            #line default
            #line hidden
WriteLiteral(");\r\n");



WriteLiteral("    }\r\n");


            
            #line 59 "..\..\Razor\Service\Broadcast\IntentFactoryRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("}");


        }
    }
}
#pragma warning restore 1591
