#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Service.Broadcast
{
    
    #line 2 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using System.CodeDom;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 6 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using Parse;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using Razor.Service;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    using Razor.Service.Broadcast;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class IntentRazor : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 10 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"

    public ServiceParser TheService { get; set; }
    public ActionBase TheAction { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");










WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


            
            #line 16 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
  
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(new Copyright().TransformText());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                      ;


            
            #line default
            #line hidden


WriteLiteral("\r\n");


            
            #line 20 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
  
    var package = TheService.Package + ".broadcast.";

    if (TheAction is IncomingAction) {package += "incoming;";}
    if (TheAction is OutgoingAction) {package += "outgoing;";}
    if (TheAction is ExternalAction) {package += "external;";}


            
            #line default
            #line hidden

            
            #line 27 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
WriteLiteral("package ");

            
            #line default
            #line hidden
            
            #line 27 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
          
            
            #line default
            #line hidden
            
            #line 27 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
     Write(package);

            
            #line default
            #line hidden
            
            #line 27 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                  

            
            #line default
            #line hidden



            
            #line 28 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
             WriteLiteral("\r\nimport android.content.Intent;\r\n\r\nimport ");

            
            #line default
            #line hidden
            
            #line 31 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
         
            
            #line default
            #line hidden
            
            #line 31 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 31 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                            
            
            #line default
            #line hidden

            
            #line 31 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                             WriteLiteral(".broadcast.");

            
            #line default
            #line hidden
            
            #line 31 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                          
            
            #line default
            #line hidden
            
            #line 31 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                     Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                            
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 32 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 foreach(var imp in TheService.Imports)
{

            
            #line default
            #line hidden
WriteLiteral("import ");


            
            #line 34 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
           
            
            #line default
            #line hidden
            
            #line 34 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
      Write(imp);

            
            #line default
            #line hidden
            
            #line 34 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
               
            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 35 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 36 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 if ((TheAction as ExternalAction) != null)
{
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
     foreach (var imp in (TheAction as ExternalAction).Imports)
    {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("import ");


            
            #line 40 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
               
            
            #line default
            #line hidden
            
            #line 40 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
          Write(imp);

            
            #line default
            #line hidden
            
            #line 40 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                   
            
            #line default
            #line hidden
WriteLiteral(";\r\n");



            
            #line 41 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    }    
}

            
            #line default
            #line hidden
WriteLiteral("/**\r\n");


            
            #line 44 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 if(TheAction is IncomingAction)
{

            
            #line default
            #line hidden
WriteLiteral(" * Intent for the {");


WriteLiteral("@link \" + ServiceWriter.ClassName(Service) +\"} \r\n");


            
            #line 47 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
if (!string.IsNullOrWhiteSpace(TheAction.ClassCommentReason))
{
    
            
            #line default
            #line hidden
            
            #line 49 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(TheAction.ClassCommentReason);

            
            #line default
            #line hidden
            
            #line 49 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n");


            
            #line 51 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral(" * [TODO: SAY THAT THE INTENT IS FOR]    \r\n");


            
            #line 55 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(" *\r\n");



WriteLiteral(" * This intent should only be created through {");


WriteLiteral("@link ");


            
            #line 57 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                   Write(ClassNames.IntentFactory(TheService));

            
            #line default
            #line hidden
WriteLiteral("#create");


            
            #line 57 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                      
            
            #line default
            #line hidden
            
            #line 57 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                 Write(TheAction.MixedCaseName);

            
            #line default
            #line hidden
            
            #line 57 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                                              
            
            #line default
            #line hidden
WriteLiteral(" function.\r\n");



WriteLiteral(" * All intended functionality and utilization is defined for that method.\r\n");



WriteLiteral(" *\r\n");



WriteLiteral(" * This intent should now be instantiated directly.\r\n");


            
            #line 61 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 62 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 if (TheAction is OutgoingAction)
{

            
            #line default
            #line hidden
WriteLiteral(" * This intent is used by the {");


WriteLiteral("@link ");


            
            #line 64 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                   Write(TheService.Name);

            
            #line default
            #line hidden
WriteLiteral("} to broadcast\r\n");


            
            #line 65 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
if (!string.IsNullOrWhiteSpace(TheAction.ClassCommentReason))
{
    
            
            #line default
            #line hidden
            
            #line 67 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(TheAction.ClassCommentReason);

            
            #line default
            #line hidden
            
            #line 67 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n");


            
            #line 69 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral(" * [TODO: Put why the service is sending this out]\r\n");


            
            #line 73 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(" *\r\n");



WriteLiteral(" * This intent should only be broadcast by {");


WriteLiteral("@link ");


            
            #line 75 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                Write(TheService.Name);

            
            #line default
            #line hidden
WriteLiteral("}\r\n");


            
            #line 76 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 77 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 if (TheAction is ExternalAction)
{

            
            #line default
            #line hidden
WriteLiteral(" * This is a wrapper for an externally defined and broadcast intent.\r\n");



WriteLiteral(" * The intent this wraps is broadcast when \r\n");


            
            #line 81 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
if (!string.IsNullOrWhiteSpace(TheAction.ClassCommentReason))
{
    
            
            #line default
            #line hidden
            
            #line 83 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(TheAction.ClassCommentReason);

            
            #line default
            #line hidden
            
            #line 83 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n");


            
            #line 85 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral(" * [TODO: THE CONDITION(S) IT\'S SENT]\r\n");


            
            #line 89 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(" *\r\n");



WriteLiteral(" * The purpose of this intent is to encapsulate and cleanly expose data from an e" +
"xternally defined intent.\r\n");



WriteLiteral(" * The service and other components utilizing this wrapper never need to know the" +
" specific ACTION or EXTRA values.\r\n");



WriteLiteral(" * All details making this intent are confined to {");


WriteLiteral("@link ");


            
            #line 93 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                       Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
WriteLiteral("}.\r\n");



WriteLiteral(" *\r\n");



WriteLiteral(" *\r\n");



WriteLiteral(" * This MUST NOT be broadcast by anyone.\r\n");


            
            #line 97 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(" *\r\n */\r\npublic final class ");


            
            #line 100 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
              Write(ClassNames.Intent(TheService, TheAction));

            
            #line default
            #line hidden
WriteLiteral(" extends ");


            
            #line 100 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
WriteLiteral(" {\r\n    /* (non-Javadoc)\r\n     * ");



            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
        WriteLiteral("@see ");

            
            #line default
            #line hidden
            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
               
            
            #line default
            #line hidden
            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
          Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral(".broadcast.");


            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                         Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden

            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                WriteLiteral("#");

            
            #line default
            #line hidden
            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                   
            
            #line default
            #line hidden
            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                              Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                                     
            
            #line default
            #line hidden

            
            #line 102 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                                      WriteLiteral("(Intent)\r\n    */\r\n    public ");

            
            #line default
            #line hidden
            
            #line 104 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
             
            
            #line default
            #line hidden
            
            #line 104 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
        Write(ClassNames.Intent(TheService, TheAction));

            
            #line default
            #line hidden
            
            #line 104 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                      
            
            #line default
            #line hidden
WriteLiteral("(final Intent intent){\r\n        super(intent);\r\n    }\r\n");


            
            #line 107 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 if(!(TheAction is ExternalAction)){

            
            #line default
            #line hidden
WriteLiteral("    /* (non-Javadoc)\r\n");



WriteLiteral("     * ");


WriteLiteral("@see ");


            
            #line 109 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                 
            
            #line default
            #line hidden
            
            #line 109 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
            Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 109 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                    
            
            #line default
            #line hidden
WriteLiteral(".broadcast.");


            
            #line 109 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                           Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
WriteLiteral("#");


            
            #line 109 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                     
            
            #line default
            #line hidden
            
            #line 109 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
            
            #line 109 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral("(String)\r\n");



WriteLiteral("    */\r\n");



WriteLiteral("    public ");


            
            #line 111 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
               
            
            #line default
            #line hidden
            
            #line 111 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
          Write(ClassNames.Intent(TheService, TheAction));

            
            #line default
            #line hidden
            
            #line 111 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                        
            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 111 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                            
            
            #line default
            #line hidden
            
            #line 111 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                       Write(TheAction.ParamsDeclarations(TheService));

            
            #line default
            #line hidden
            
            #line 111 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                     
            
            #line default
            #line hidden
WriteLiteral("){\r\n");



WriteLiteral("        super(");


            
            #line 112 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 112 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
             Write(TheAction.FieldName(TheService));

            
            #line default
            #line hidden
            
            #line 112 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                  
            
            #line default
            #line hidden
WriteLiteral(");\r\n");


            
            #line 113 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
if (TheAction is IncomingAction)
{

            
            #line default
            #line hidden
WriteLiteral("        setComponent(getServiceComponentName());\r\n");


            
            #line 116 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("        ");


            
            #line 118 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
     Write(TheAction.ConstructorPuts(TheService));

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("    }   \r\n");


            
            #line 120 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden

            
            #line 121 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 foreach (var extraKey in TheAction.ParamExtraKeys)
{
    if (TheService.Extras.InternalAndPublicExtras.All(x => x.Name != extraKey))
    {
        var extra = TheService.Extras.ExternalExtraGroups.First(x => x.ActionKey == TheAction.Name).ExternalExtras.First(x => x.Name == extraKey);

            
            #line default
            #line hidden
WriteLiteral("\r\n");




            
            #line 127 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    
            
            #line default
            #line hidden
            
            #line 127 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(extra.PutMethodComment());

            
            #line default
            #line hidden
            
            #line 127 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                             
            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("    ");

WriteLiteral("protected ");


            
            #line 128 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 128 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
              Write(extra.PutMethodDefinition());

            
            #line default
            #line hidden
            
            #line 128 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                               
            
            #line default
            #line hidden
WriteLiteral(" {\r\n");



WriteLiteral("    ");

WriteLiteral("    putExtra(");


            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                      
            
            #line default
            #line hidden
            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                 Write(extra.FieldName());

            
            #line default
            #line hidden
            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                        
            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                              
            
            #line default
            #line hidden
            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                         Write(extra.ParamName());

            
            #line default
            #line hidden
            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                 
            
            #line default
            #line hidden

            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                     
            
            #line default
            #line hidden
            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                 Write(extra.IsEnum ? ".ordinal()" : "");

            
            #line default
            #line hidden
            
            #line 129 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                         
            
            #line default
            #line hidden
WriteLiteral(");\r\n");



WriteLiteral("    ");

WriteLiteral("}\r\n");


            
            #line 131 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    }
}

            
            #line default
            #line hidden

            
            #line 133 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
     foreach (var extra in TheAction.GetterExtraList(TheService))
    {
    if (TheService.Extras.InternalAndPublicExtras.Any(overExtra => overExtra.Name == extra.Name))
    {
    if (TheAction is ExternalAction)
    {

            
            #line default
            #line hidden
            
            #line 139 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(extra.GetMethodImplComment());

            
            #line default
            #line hidden
            
            #line 139 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                             

            
            #line default
            #line hidden
            
            #line 140 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(extra.GetMethodImpl("public"));

            
            #line default
            #line hidden
            
            #line 140 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                              
    }
    else
    {   

            
            #line default
            #line hidden
WriteLiteral("    /* (non-Javadoc)\r\n");



WriteLiteral("     * ");


WriteLiteral("@see ");


            
            #line 145 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                 
            
            #line default
            #line hidden
            
            #line 145 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
            Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 145 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                    
            
            #line default
            #line hidden
WriteLiteral(".broadcast.");


            
            #line 145 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                           Write(ClassNames.IntentBase(TheService));

            
            #line default
            #line hidden
WriteLiteral("#");


            
            #line 145 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                     
            
            #line default
            #line hidden
            
            #line 145 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                Write(extra.GetMethodName());

            
            #line default
            #line hidden
            
            #line 145 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                                                                           
            
            #line default
            #line hidden
WriteLiteral("()\r\n");



WriteLiteral("     */\r\n");



WriteLiteral("    ");


WriteLiteral("@Override \r\n");


            
            #line 148 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"

            
            #line default
            #line hidden
            
            #line 148 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(extra.GetMethodOverride("public"));

            
            #line default
            #line hidden
            
            #line 148 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                  
    }
    }
    else
    {

            
            #line default
            #line hidden
            
            #line 153 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(extra.GetMethodImplComment());

            
            #line default
            #line hidden
            
            #line 153 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                             

            
            #line default
            #line hidden
            
            #line 154 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
Write(extra.GetMethodImpl("public"));

            
            #line default
            #line hidden
            
            #line 154 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                              
    }
    }

            
            #line default
            #line hidden

            
            #line 157 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
  
    var doToString = false;
    foreach (var extra in TheAction.GetterExtraList(TheService))
    {
        if (TheService.Extras.DistinctExtras.Any(overExtra => overExtra.Name == extra.Name))
        {
            doToString = true;
        }
    }


            
            #line default
            #line hidden

            
            #line 167 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
 if(doToString)
{

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("    ");


WriteLiteral("@Override\r\n");



WriteLiteral("    public String toString(){\r\n");



WriteLiteral("        return super.toString(\r\n");


            
            #line 173 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
    var list = new List<string>();
                        foreach (var extra in TheAction.GetterExtraList(TheService))
                        {
                            if (TheService.Extras.DistinctExtras.Any(overExtra => overExtra.Name == extra.Name))
                            {
                                list.Add("            \"[" + extra.GetMethodName() + "()=\" + " + extra.GetMethodName() + "() + \"]\"");
                            }
                        }
            
            
            #line default
            #line hidden
            
            #line 181 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
       Write(string.Join(" +" + Environment.NewLine, list));

            
            #line default
            #line hidden
            
            #line 181 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
                                                          

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("        );\r\n");



WriteLiteral("    }\r\n");


            
            #line 185 "..\..\Razor\Service\Broadcast\IntentRazor.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("}");


        }
    }
}
#pragma warning restore 1591
