#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidServiceGenerator.Razor.Service.Database
{
    
    #line 2 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
    using Parse;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
    using Razor.Common;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
    using Razor.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DatabaseRazor : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 10 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"

    public ServiceParser TheService { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


            
            #line 13 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
  
    //const strin wontCompile;
    var className = TheService.Name + "Database";


            
            #line default
            #line hidden
WriteLiteral("\r\n}\r\n");



WriteLiteral("\r\n");


            
            #line 20 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
   new Copyright { }.TransformText();

            
            #line default
            #line hidden
WriteLiteral("\r\n");




            
            #line 22 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
             WriteLiteral("\r\npackage ");

            
            #line default
            #line hidden
            
            #line 23 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
          
            
            #line default
            #line hidden
            
            #line 23 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
     Write(TheService.Package);

            
            #line default
            #line hidden
            
            #line 23 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
                             
            
            #line default
            #line hidden
WriteLiteral(".database;\r\n\r\n");



WriteLiteral(@"
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

import android.database.sqlite.SQLiteOpenHelper;

/**
 * TODO: Describe what this class does
 */
public final class ");


            
            #line 36 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
              Write(className);

            
            #line default
            #line hidden
WriteLiteral(" extends SQLiteOpenHelper {\r\n\r\n    private static ");


            
            #line 38 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
              Write(className);

            
            #line default
            #line hidden

            
            #line 38 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
                             WriteLiteral(" _instance = new ");

            
            #line default
            #line hidden
            
            #line 38 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 38 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
                                           Write(className);

            
            #line default
            #line hidden
            
            #line 38 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
                                                          
            
            #line default
            #line hidden
WriteLiteral("(Application.getInstance());\r\n\r\n    public static ");


            
            #line 40 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
             Write(className);

            
            #line default
            #line hidden

            
            #line 40 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
                            WriteLiteral(@" getInstance() {
        return _instance;
    }
    
    private static final int DATABASE_VERSION = 1;
    
    // Database name
    private static final String DATABASE_NAME = null; //TODO: Name Me

    // Table name
    private static final String TABLE_name_me = ""name_me"";//TODO: Name me
    
    //Column names
    private static final String COLUMN_name_me = ""name_me"";//TODO: Name me
    /* Probably will want to expand the number of columns */
    

    private static final String CREATE_TABLE_name_me = 
            ""CREATE TABLE "" + TABLE_name_me + "" ("" +
                COLUMN_name_me + "" TEXT, "" +
                /* Probably gonna have more columns - if not, the comma above will need to be removed */
            "");"";

    private ");

            
            #line default
            #line hidden
            
            #line 63 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
              
            
            #line default
            #line hidden
            
            #line 63 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
         Write(className);

            
            #line default
            #line hidden
            
            #line 63 "..\..\Razor\Service\Database\DatabaseRazor.cshtml"
                        
            
            #line default
            #line hidden
WriteLiteral("(final Context context) {\r\n        super(context.getApplicationContext(), DATABAS" +
"E_NAME, null, DATABASE_VERSION);\r\n    }\r\n    \r\n    ");


WriteLiteral("@Override\r\n    public void onCreate(SQLiteDatabase db) {\r\n        db.execSQL(TABL" +
"E_name_me);\r\n\r\n    }\r\n\r\n    ");


WriteLiteral("@Override\r\n    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVe" +
"rsion) {\r\n        if (db != null) {\r\n            db.execSQL(\"DROP TABLE IF EXIST" +
"S \" + TABLE_name_me);\r\n            onCreate(db);\r\n        }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
